# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
  config.vm.box     = "opscode-ubuntu-14.04"
  # config.vm.box_url = "http://files.vagrantup.com/precise64.box"
  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", 512, "--cpus", 2]
  end

  # Mount our repo onto /etc/puppet
  config.vm.synced_folder "../", "/etc/puppet"

  # Run our Puppet shell script
  config.vm.provision "shell" do |s|
    s.path = "update-puppet.sh"
  end

  config.vm.hostname = "localdev.example.com"
end