name    'CopperEgg-copperegg'
version '1.0.3'
author  'Scott C. Johnson'
license 'BSD'
summary 'Install and configure CopperEgg collector; manage RevealUptime probes.'
description 'This module will install the CopperEgg collector for the following operating systems: Linux 2.6 and above, FreeBSD 7.0 and above. Supported Linux distros include Centos5 and above, Ubuntu 8.04 and above, SuSE, etc. It also contains a type and provider for managing RevealUptime probes.'
project_page 'https://github.com/CopperEgg/revealcloud-puppet'
