name    'puppet-copperegg'
version '0.0.5'
author  'Scott C. Johnson'
license 'BSD'
summary 'Install and configure CopperEgg collector.'
description 'This module will insall the CopperEgg collector for the following operating systems: Linux 2.6 and above, FreeBSD 7.0 and above. Supported Linux distros include Centos5 and above, Ubuntu 8.04 and above, SuSE, etc.'
project_page 'https://github.com/sjohnsoncopperegg/puppet-copperegg'
